### ISSUE TITLE
Is it possible to change the title of the indicator group to "VGGT- 16.1 (expropriation and compensation) indicators"?

### ISSUE THREAD

**Issue by ntagliar** [landportal/js-view-coda#9]
This was Lisette's comment and I agree

**Comment by dayures** [comment]
![captura](https://cloud.githubusercontent.com/assets/1654811/21841158/46c35d10-d7e1-11e6-9e98-4f9b2005ce12.PNG)

The values expected are:
VGGT 16.1 Expropriation and Compensation Eligibility Indicators
VGGT 16.3 Fair Valuation and Prompt Compensation Indicators

**Comment by dayures** [comment]
@jcr , currently this requires a change in js/lbvis.vggt.js around line 40

**Comment by dayures** [comment]
fixed in ef853d797b34937b646def8a1dc214ce0a093d04
